
name: Formatting code
on:
  push:
    branches:
      - master
jobs:
  auto_format:
    # Check if the PR is not from a fork
    if: github.repository == 'waterlooairlock/Data-Acquisition'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix C++ formatting
        uses: HorstBaerbel/action-clang-format@1.4
        with:
          scandir: ',\Arduino_Code,\Arduino_Code\Shared_libs\data_acquisition_lib'
          excludedirs: ',\Arduino_Code\Shared_libs,\Arduino_Code\*\lib'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
          style: 'file' # Create a custom .clang-format file
      - name: Fix Python Formatting
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --exclude=Python_Backend/backend_env Python_Backend
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'waterlooairlock'
          git config --global user.email 'Watlockemail@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated Formatting Fixes"
          git push
